version: '3.9'
services:
  app:
    container_name: golang_google_sheets_container
    build: 
      context: .
      dockerfile: Dockerfile.multistage
    ports:
      - ${PORT}:${PORT}
    networks:
      - learning
    depends_on:
      - redis-google-sheets-db
  redis-google-sheets-db:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    container_name: redis-google-sheets-db
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    networks:
      - learning

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge